"""empty message

Revision ID: 4faf48dea7d7
Revises: 79e2aa50d602
Create Date: 2023-07-01 19:10:44.063498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faf48dea7d7'
down_revision = '79e2aa50d602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('crag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crag_name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.String(length=150), nullable=True),
    sa.Column('longitude', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('rock_type', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crag')
    op.drop_table('user')
    # ### end Alembic commands ###
